[package]
name = "chess_rust"
version = "0.1.0"
authors = ["Gary Guyot <gary.guyot@telecomnancy.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.5"
text_io = "0.1.8"